job_data = [{"employee_id":1,"employee_name":"Addy Capponeer","job_title":"Desktop Support Technician","department":"Research and Development","salary":88281.38,"hire_date":"7/3/2009","years_of_service":"error: expected numeric","performance_rating":4.1,"manager_name":"Ilyse Le Noire","team_size":5,"location":"Chicago","remote_work":false,"vacation_days_remaining":8,"overtime_hours":10.0,"email_address":"ile0@tmall.com"},
{"employee_id":2,"employee_name":"L;urette Senn","job_title":"Research Assistant IV","department":"Engineering","salary":102036.3,"hire_date":"1/4/2015","years_of_service":"error: expected numeric","performance_rating":4.2,"manager_name":"Karalynn Carthew","team_size":13,"location":"Houston","remote_work":false,"vacation_days_remaining":10,"overtime_hours":18.1,"email_address":"kcarthew1@usnews.com"},
{"employee_id":3,"employee_name":"Harp Feehely","job_title":"Assistant Media Planner","department":"Training","salary":32638.67,"hire_date":"6/23/2019","years_of_service":"error: expected numeric","performance_rating":1.4,"manager_name":"Bertina Gooden","team_size":10,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":24,"overtime_hours":5.4,"email_address":"bgooden2@cargocollective.com"},
{"employee_id":4,"employee_name":"Prentiss Tourner","job_title":"Chief Design Engineer","department":"Human Resources","salary":45534.7,"hire_date":"1/18/2015","years_of_service":"error: expected numeric","performance_rating":3.1,"manager_name":"Craggy Parriss","team_size":16,"location":"Chicago","remote_work":true,"vacation_days_remaining":4,"overtime_hours":4.7,"email_address":"cparriss3@theatlantic.com"},
{"employee_id":5,"employee_name":"Amalee Leahy","job_title":"Office Assistant I","department":"Engineering","salary":88552.63,"hire_date":"3/9/2006","years_of_service":"error: expected numeric","performance_rating":4.4,"manager_name":"Hugo Little","team_size":6,"location":"Miami","remote_work":true,"vacation_days_remaining":4,"overtime_hours":2.7,"email_address":"hlittle4@blog.com"},
{"employee_id":6,"employee_name":"Giralda Brisseau","job_title":"Analog Circuit Design manager","department":"Legal","salary":84401.58,"hire_date":"9/30/2017","years_of_service":"error: expected numeric","performance_rating":1.8,"manager_name":"Doretta Martinie","team_size":3,"location":"New York","remote_work":true,"vacation_days_remaining":2,"overtime_hours":15.5,"email_address":"dmartinie5@vimeo.com"},
{"employee_id":7,"employee_name":"Shandie Gealy","job_title":"Marketing Assistant","department":"Business Development","salary":67052.11,"hire_date":"7/13/2006","years_of_service":"error: expected numeric","performance_rating":4.4,"manager_name":"Rozele Ertelt","team_size":11,"location":"Miami","remote_work":false,"vacation_days_remaining":30,"overtime_hours":7.7,"email_address":"rertelt6@printfriendly.com"},
{"employee_id":8,"employee_name":"Aggy Berecloth","job_title":"Registered Nurse","department":"Sales","salary":128423.87,"hire_date":"6/25/2003","years_of_service":"error: expected numeric","performance_rating":4.5,"manager_name":"Kurt Rosengart","team_size":17,"location":"Houston","remote_work":true,"vacation_days_remaining":23,"overtime_hours":17.1,"email_address":"krosengart7@prnewswire.com"},
{"employee_id":9,"employee_name":"Alvin Youde","job_title":"Biostatistician III","department":"Accounting","salary":32074.65,"hire_date":"4/7/2020","years_of_service":"error: expected numeric","performance_rating":4.8,"manager_name":"Niels Aumerle","team_size":12,"location":"New York","remote_work":false,"vacation_days_remaining":28,"overtime_hours":17.0,"email_address":"naumerle8@intel.com"},
{"employee_id":10,"employee_name":"Antonin Dabling","job_title":"Budget/Accounting Analyst IV","department":"Legal","salary":118556.82,"hire_date":"2/9/2016","years_of_service":"error: expected numeric","performance_rating":1.3,"manager_name":"Clayborn Mallison","team_size":6,"location":"Chicago","remote_work":false,"vacation_days_remaining":29,"overtime_hours":0.4,"email_address":"cmallison9@vistaprint.com"},
{"employee_id":11,"employee_name":"Fonsie Assinder","job_title":"Nuclear Power Engineer","department":"Research and Development","salary":127090.94,"hire_date":"7/5/2018","years_of_service":"error: expected numeric","performance_rating":1.1,"manager_name":"Valentin Varga","team_size":11,"location":"Miami","remote_work":true,"vacation_days_remaining":21,"overtime_hours":10.0,"email_address":"vvargaa@nytimes.com"},
{"employee_id":12,"employee_name":"Casar Ollier","job_title":"General Manager","department":"Business Development","salary":101791.88,"hire_date":"2/24/2010","years_of_service":"error: expected numeric","performance_rating":3.5,"manager_name":"Alvira Chubb","team_size":9,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":10,"overtime_hours":15.3,"email_address":"achubbb@webeden.co.uk"},
{"employee_id":13,"employee_name":"Durand Yearn","job_title":"Senior Financial Analyst","department":"Engineering","salary":135100.16,"hire_date":"10/10/2012","years_of_service":"error: expected numeric","performance_rating":4.7,"manager_name":"Cathe Tomaszewski","team_size":7,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":16,"overtime_hours":14.5,"email_address":"ctomaszewskic@instagram.com"},
{"employee_id":14,"employee_name":"Becka Iorizzo","job_title":"Environmental Tech","department":"Services","salary":46489.43,"hire_date":"10/25/2000","years_of_service":"error: expected numeric","performance_rating":3.9,"manager_name":"Belvia Medling","team_size":18,"location":"New York","remote_work":true,"vacation_days_remaining":27,"overtime_hours":17.5,"email_address":"bmedlingd@house.gov"},
{"employee_id":15,"employee_name":"Karalynn Pym","job_title":"Sales Representative","department":"Legal","salary":142716.52,"hire_date":"7/1/2017","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Torin Seacombe","team_size":2,"location":"Miami","remote_work":true,"vacation_days_remaining":26,"overtime_hours":7.8,"email_address":"tseacombee@tinypic.com"},
{"employee_id":16,"employee_name":"Korney Lowdeane","job_title":"VP Accounting","department":"Business Development","salary":128806.29,"hire_date":"6/20/2014","years_of_service":"error: expected numeric","performance_rating":4.3,"manager_name":"Arnie Ipgrave","team_size":8,"location":"New York","remote_work":true,"vacation_days_remaining":24,"overtime_hours":17.0,"email_address":"aipgravef@cdbaby.com"},
{"employee_id":17,"employee_name":"Husein Wollaston","job_title":"Analog Circuit Design manager","department":"Business Development","salary":139301.88,"hire_date":"7/12/2018","years_of_service":"error: expected numeric","performance_rating":1.1,"manager_name":"Mavra Terbruggen","team_size":1,"location":"Houston","remote_work":false,"vacation_days_remaining":1,"overtime_hours":16.7,"email_address":"mterbruggeng@marriott.com"},
{"employee_id":18,"employee_name":"Percival Cumberlidge","job_title":"Compensation Analyst","department":"Product Management","salary":43780.75,"hire_date":"12/25/2015","years_of_service":"error: expected numeric","performance_rating":5.0,"manager_name":"Teodoor Cudby","team_size":15,"location":"New York","remote_work":true,"vacation_days_remaining":3,"overtime_hours":8.6,"email_address":"tcudbyh@icio.us"},
{"employee_id":19,"employee_name":"Quentin Matyukon","job_title":"Senior Quality Engineer","department":"Sales","salary":64332.67,"hire_date":"9/2/2012","years_of_service":"error: expected numeric","performance_rating":1.3,"manager_name":"Hallie Francklyn","team_size":17,"location":"Chicago","remote_work":false,"vacation_days_remaining":14,"overtime_hours":19.5,"email_address":"hfrancklyni@tripadvisor.com"},
{"employee_id":20,"employee_name":"Tomi Phillcock","job_title":"Analog Circuit Design manager","department":"Research and Development","salary":32443.64,"hire_date":"9/15/2022","years_of_service":"error: expected numeric","performance_rating":3.1,"manager_name":"Margi Hollingsby","team_size":17,"location":"New York","remote_work":false,"vacation_days_remaining":18,"overtime_hours":1.4,"email_address":"mhollingsbyj@youtube.com"},
{"employee_id":21,"employee_name":"Rhianon Potier","job_title":"Associate Professor","department":"Human Resources","salary":149511.14,"hire_date":"5/23/2000","years_of_service":"error: expected numeric","performance_rating":1.9,"manager_name":"Nicolais Veness","team_size":14,"location":"Chicago","remote_work":false,"vacation_days_remaining":26,"overtime_hours":5.3,"email_address":"nvenessk@harvard.edu"},
{"employee_id":22,"employee_name":"Alla Kleisel","job_title":"Actuary","department":"Accounting","salary":83775.19,"hire_date":"2/8/2003","years_of_service":"error: expected numeric","performance_rating":4.8,"manager_name":"Gilemette Sherville","team_size":2,"location":"Houston","remote_work":true,"vacation_days_remaining":8,"overtime_hours":4.6,"email_address":"gshervillel@sphinn.com"},
{"employee_id":23,"employee_name":"Shelba Delagua","job_title":"Junior Executive","department":"Research and Development","salary":75363.92,"hire_date":"4/4/2015","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Fletch Paull","team_size":20,"location":"Miami","remote_work":false,"vacation_days_remaining":12,"overtime_hours":8.6,"email_address":"fpaullm@feedburner.com"},
{"employee_id":24,"employee_name":"Bree Cockitt","job_title":"Design Engineer","department":"Engineering","salary":137464.76,"hire_date":"1/8/2020","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Asa Wolford","team_size":14,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":28,"overtime_hours":1.2,"email_address":"awolfordn@linkedin.com"},
{"employee_id":25,"employee_name":"Orelee Kingswoode","job_title":"Assistant Media Planner","department":"Sales","salary":36213.38,"hire_date":"3/31/2015","years_of_service":"error: expected numeric","performance_rating":4.6,"manager_name":"Danila Mingard","team_size":13,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":23,"overtime_hours":1.8,"email_address":"dmingardo@live.com"},
{"employee_id":26,"employee_name":"Shaun McCullagh","job_title":"Pharmacist","department":"Training","salary":137928.96,"hire_date":"11/17/2001","years_of_service":"error: expected numeric","performance_rating":1.2,"manager_name":"Dierdre Millott","team_size":6,"location":"Miami","remote_work":false,"vacation_days_remaining":19,"overtime_hours":14.8,"email_address":"dmillottp@nymag.com"},
{"employee_id":27,"employee_name":"Caresse Senogles","job_title":"Information Systems Manager","department":"Training","salary":147756.76,"hire_date":"3/2/2008","years_of_service":"error: expected numeric","performance_rating":3.3,"manager_name":"Morty Berk","team_size":16,"location":"New York","remote_work":false,"vacation_days_remaining":24,"overtime_hours":2.7,"email_address":"mberkq@skyrock.com"},
{"employee_id":28,"employee_name":"Laure Giacobelli","job_title":"Recruiter","department":"Human Resources","salary":124529.32,"hire_date":"2/1/2016","years_of_service":"error: expected numeric","performance_rating":2.7,"manager_name":"Phoebe Grayshan","team_size":7,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":26,"overtime_hours":16.5,"email_address":"pgrayshanr@ftc.gov"},
{"employee_id":29,"employee_name":"Megan Sawnwy","job_title":"Database Administrator III","department":"Training","salary":63153.51,"hire_date":"4/29/2004","years_of_service":"error: expected numeric","performance_rating":4.7,"manager_name":"Hamlin Allsup","team_size":6,"location":"Chicago","remote_work":true,"vacation_days_remaining":8,"overtime_hours":7.2,"email_address":"hallsups@cpanel.net"},
{"employee_id":30,"employee_name":"Brittan Anderl","job_title":"Business Systems Development Analyst","department":"Legal","salary":37734.28,"hire_date":"4/6/2019","years_of_service":"error: expected numeric","performance_rating":3.1,"manager_name":"Aurel Denyakin","team_size":19,"location":"New York","remote_work":true,"vacation_days_remaining":0,"overtime_hours":4.9,"email_address":"adenyakint@nsw.gov.au"},
{"employee_id":31,"employee_name":"Reynold Downing","job_title":"General Manager","department":"Marketing","salary":108960.02,"hire_date":"9/4/2006","years_of_service":"error: expected numeric","performance_rating":3.5,"manager_name":"Donia Jacquet","team_size":20,"location":"Miami","remote_work":true,"vacation_days_remaining":1,"overtime_hours":10.7,"email_address":"djacquetu@geocities.jp"},
{"employee_id":32,"employee_name":"Chelsae Ledwidge","job_title":"Technical Writer","department":"Accounting","salary":90155.73,"hire_date":"4/4/2021","years_of_service":"error: expected numeric","performance_rating":2.6,"manager_name":"Hetty Gerretsen","team_size":1,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":19,"overtime_hours":9.7,"email_address":"hgerretsenv@msn.com"},
{"employee_id":33,"employee_name":"Maximilianus Hargitt","job_title":"Cost Accountant","department":"Support","salary":112647.59,"hire_date":"1/9/2000","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Tymothy Offner","team_size":15,"location":"Miami","remote_work":true,"vacation_days_remaining":17,"overtime_hours":3.7,"email_address":"toffnerw@ucla.edu"},
{"employee_id":34,"employee_name":"Carina Tovey","job_title":"Professor","department":"Services","salary":36164.7,"hire_date":"4/23/2021","years_of_service":"error: expected numeric","performance_rating":3.8,"manager_name":"Courtnay Shenton","team_size":15,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":30,"overtime_hours":7.5,"email_address":"cshentonx@sciencedaily.com"},
{"employee_id":35,"employee_name":"Seamus Beart","job_title":"Food Chemist","department":"Services","salary":128916.87,"hire_date":"12/6/2012","years_of_service":"error: expected numeric","performance_rating":3.9,"manager_name":"Sergent Pinney","team_size":18,"location":"Houston","remote_work":false,"vacation_days_remaining":3,"overtime_hours":9.3,"email_address":"spinneyy@answers.com"},
{"employee_id":36,"employee_name":"Shelden Tredwell","job_title":"Tax Accountant","department":"Engineering","salary":88561.88,"hire_date":"8/15/2021","years_of_service":"error: expected numeric","performance_rating":3.3,"manager_name":"Mira Kingsnorth","team_size":6,"location":"New York","remote_work":false,"vacation_days_remaining":11,"overtime_hours":11.0,"email_address":"mkingsnorthz@ustream.tv"},
{"employee_id":37,"employee_name":"Allard Lorait","job_title":"Human Resources Manager","department":"Sales","salary":149369.72,"hire_date":"9/19/2013","years_of_service":"error: expected numeric","performance_rating":3.2,"manager_name":"Kath Peller","team_size":7,"location":"Miami","remote_work":false,"vacation_days_remaining":12,"overtime_hours":14.6,"email_address":"kpeller10@sphinn.com"},
{"employee_id":38,"employee_name":"Belvia Lysaght","job_title":"Software Test Engineer II","department":"Accounting","salary":95026.0,"hire_date":"1/3/2017","years_of_service":"error: expected numeric","performance_rating":2.8,"manager_name":"Mattheus Baldwin","team_size":20,"location":"New York","remote_work":true,"vacation_days_remaining":20,"overtime_hours":12.2,"email_address":"mbaldwin11@hatena.ne.jp"},
{"employee_id":39,"employee_name":"Cheston Tyres","job_title":"VP Sales","department":"Sales","salary":63730.35,"hire_date":"2/11/2012","years_of_service":"error: expected numeric","performance_rating":3.2,"manager_name":"Rivy Fair","team_size":4,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":10,"overtime_hours":6.0,"email_address":"rfair12@bloomberg.com"},
{"employee_id":40,"employee_name":"Danni Febvre","job_title":"Assistant Manager","department":"Research and Development","salary":111880.22,"hire_date":"2/3/2000","years_of_service":"error: expected numeric","performance_rating":2.3,"manager_name":"Ashby Mack","team_size":8,"location":"Miami","remote_work":false,"vacation_days_remaining":25,"overtime_hours":12.7,"email_address":"amack13@wikispaces.com"},
{"employee_id":41,"employee_name":"Antoni Hendrick","job_title":"Account Representative II","department":"Business Development","salary":98215.96,"hire_date":"12/21/2020","years_of_service":"error: expected numeric","performance_rating":3.6,"manager_name":"Fredelia Brumen","team_size":16,"location":"Houston","remote_work":false,"vacation_days_remaining":14,"overtime_hours":7.9,"email_address":"fbrumen14@cnet.com"},
{"employee_id":42,"employee_name":"Karoline Kaveney","job_title":"Food Chemist","department":"Support","salary":48190.21,"hire_date":"1/20/2015","years_of_service":"error: expected numeric","performance_rating":1.7,"manager_name":"Hew Mowlam","team_size":11,"location":"Chicago","remote_work":false,"vacation_days_remaining":27,"overtime_hours":4.8,"email_address":"hmowlam15@nydailynews.com"},
{"employee_id":43,"employee_name":"Susi Phinnessy","job_title":"Structural Engineer","department":"Product Management","salary":30487.76,"hire_date":"5/23/2011","years_of_service":"error: expected numeric","performance_rating":3.8,"manager_name":"Albertina Cobain","team_size":10,"location":"Houston","remote_work":true,"vacation_days_remaining":7,"overtime_hours":18.3,"email_address":"acobain16@opera.com"},
{"employee_id":44,"employee_name":"Dante Messier","job_title":"Automation Specialist II","department":"Research and Development","salary":148285.52,"hire_date":"7/5/2007","years_of_service":"error: expected numeric","performance_rating":2.8,"manager_name":"Rochella Charlon","team_size":20,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":16,"overtime_hours":19.4,"email_address":"rcharlon17@barnesandnoble.com"},
{"employee_id":45,"employee_name":"Siegfried Girtin","job_title":"Nurse","department":"Engineering","salary":148917.52,"hire_date":"6/15/2019","years_of_service":"error: expected numeric","performance_rating":2.5,"manager_name":"Zorine Cranstoun","team_size":11,"location":"Chicago","remote_work":true,"vacation_days_remaining":4,"overtime_hours":19.4,"email_address":"zcranstoun18@ca.gov"},
{"employee_id":46,"employee_name":"Midge Doy","job_title":"Web Developer IV","department":"Business Development","salary":142209.61,"hire_date":"4/8/2021","years_of_service":"error: expected numeric","performance_rating":1.6,"manager_name":"Norene Folder","team_size":2,"location":"New York","remote_work":false,"vacation_days_remaining":9,"overtime_hours":0.4,"email_address":"nfolder19@instagram.com"},
{"employee_id":47,"employee_name":"Jedediah Meggison","job_title":"Staff Scientist","department":"Product Management","salary":53118.83,"hire_date":"10/18/2012","years_of_service":"error: expected numeric","performance_rating":4.8,"manager_name":"Griff Malshinger","team_size":16,"location":"New York","remote_work":true,"vacation_days_remaining":26,"overtime_hours":9.8,"email_address":"gmalshinger1a@buzzfeed.com"},
{"employee_id":48,"employee_name":"Vale Bertwistle","job_title":"Research Nurse","department":"Sales","salary":66000.64,"hire_date":"8/6/2009","years_of_service":"error: expected numeric","performance_rating":1.5,"manager_name":"Opaline Bonnavant","team_size":19,"location":"New York","remote_work":false,"vacation_days_remaining":9,"overtime_hours":7.4,"email_address":"obonnavant1b@amazonaws.com"},
{"employee_id":49,"employee_name":"Frederica Palfrie","job_title":"Developer IV","department":"Support","salary":88306.95,"hire_date":"11/2/2006","years_of_service":"error: expected numeric","performance_rating":1.3,"manager_name":"Elfie Hindsberg","team_size":12,"location":"New York","remote_work":false,"vacation_days_remaining":9,"overtime_hours":15.7,"email_address":"ehindsberg1c@nhs.uk"},
{"employee_id":50,"employee_name":"Davey Prestney","job_title":"Account Coordinator","department":"Business Development","salary":95418.07,"hire_date":"3/17/2000","years_of_service":"error: expected numeric","performance_rating":1.5,"manager_name":"Barr Steger","team_size":16,"location":"Miami","remote_work":false,"vacation_days_remaining":27,"overtime_hours":11.7,"email_address":"bsteger1d@zimbio.com"},
{"employee_id":51,"employee_name":"Tiffy Clayden","job_title":"Nurse Practicioner","department":"Business Development","salary":84628.67,"hire_date":"1/7/2012","years_of_service":"error: expected numeric","performance_rating":4.9,"manager_name":"Therese Knotte","team_size":2,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":9,"overtime_hours":15.0,"email_address":"tknotte1e@latimes.com"},
{"employee_id":52,"employee_name":"Stacy Pabst","job_title":"Geologist I","department":"Legal","salary":102755.33,"hire_date":"2/22/2016","years_of_service":"error: expected numeric","performance_rating":3.2,"manager_name":"Freemon Jaggard","team_size":1,"location":"Houston","remote_work":false,"vacation_days_remaining":21,"overtime_hours":10.0,"email_address":"fjaggard1f@clickbank.net"},
{"employee_id":53,"employee_name":"Willi Edlyne","job_title":"Research Associate","department":"Human Resources","salary":109480.48,"hire_date":"9/3/2004","years_of_service":"error: expected numeric","performance_rating":2.1,"manager_name":"Jackelyn Royste","team_size":17,"location":"Miami","remote_work":false,"vacation_days_remaining":20,"overtime_hours":5.2,"email_address":"jroyste1g@surveymonkey.com"},
{"employee_id":54,"employee_name":"Dene Milkin","job_title":"Internal Auditor","department":"Services","salary":50844.65,"hire_date":"9/9/2008","years_of_service":"error: expected numeric","performance_rating":4.2,"manager_name":"Terry Heinschke","team_size":16,"location":"Houston","remote_work":false,"vacation_days_remaining":22,"overtime_hours":4.5,"email_address":"theinschke1h@360.cn"},
{"employee_id":55,"employee_name":"Guillermo Elcox","job_title":"Computer Systems Analyst III","department":"Legal","salary":50664.42,"hire_date":"6/2/2014","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Carolyne Winslade","team_size":19,"location":"New York","remote_work":true,"vacation_days_remaining":3,"overtime_hours":12.5,"email_address":"cwinslade1i@usgs.gov"},
{"employee_id":56,"employee_name":"Penelope Mosey","job_title":"Electrical Engineer","department":"Sales","salary":31287.51,"hire_date":"11/23/2009","years_of_service":"error: expected numeric","performance_rating":3.9,"manager_name":"Damon Worrell","team_size":6,"location":"New York","remote_work":true,"vacation_days_remaining":29,"overtime_hours":5.6,"email_address":"dworrell1j@privacy.gov.au"},
{"employee_id":57,"employee_name":"Lavinia Dulling","job_title":"Associate Professor","department":"Business Development","salary":144459.42,"hire_date":"6/9/2010","years_of_service":"error: expected numeric","performance_rating":4.6,"manager_name":"Juana Schach","team_size":14,"location":"New York","remote_work":false,"vacation_days_remaining":3,"overtime_hours":5.7,"email_address":"jschach1k@cornell.edu"},
{"employee_id":58,"employee_name":"Beilul McAllen","job_title":"VP Sales","department":"Research and Development","salary":72998.6,"hire_date":"7/25/2021","years_of_service":"error: expected numeric","performance_rating":4.7,"manager_name":"Jaquelin Nolli","team_size":3,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":20,"overtime_hours":10.0,"email_address":"jnolli1l@skyrock.com"},
{"employee_id":59,"employee_name":"Jaquenette Lukes","job_title":"Programmer Analyst IV","department":"Engineering","salary":136737.41,"hire_date":"10/5/2015","years_of_service":"error: expected numeric","performance_rating":1.9,"manager_name":"Cullin Sahlstrom","team_size":13,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":5,"overtime_hours":0.3,"email_address":"csahlstrom1m@nba.com"},
{"employee_id":60,"employee_name":"Hube Bursnell","job_title":"Senior Editor","department":"Support","salary":139746.03,"hire_date":"7/2/2015","years_of_service":"error: expected numeric","performance_rating":3.2,"manager_name":"Martie Shepherd","team_size":15,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":28,"overtime_hours":4.0,"email_address":"mshepherd1n@rambler.ru"},
{"employee_id":61,"employee_name":"Zia Lerwill","job_title":"GIS Technical Architect","department":"Support","salary":83135.67,"hire_date":"1/11/2008","years_of_service":"error: expected numeric","performance_rating":2.2,"manager_name":"Fanchon Rabbet","team_size":19,"location":"New York","remote_work":false,"vacation_days_remaining":0,"overtime_hours":12.5,"email_address":"frabbet1o@tmall.com"},
{"employee_id":62,"employee_name":"Ariana Kohrsen","job_title":"Senior Sales Associate","department":"Sales","salary":33071.32,"hire_date":"2/2/2020","years_of_service":"error: expected numeric","performance_rating":2.2,"manager_name":"Eirena Newbery","team_size":19,"location":"Miami","remote_work":false,"vacation_days_remaining":11,"overtime_hours":4.2,"email_address":"enewbery1p@slate.com"},
{"employee_id":63,"employee_name":"Lanny Smithers","job_title":"General Manager","department":"Services","salary":34578.56,"hire_date":"12/12/2022","years_of_service":"error: expected numeric","performance_rating":3.3,"manager_name":"Tome Portchmouth","team_size":8,"location":"Chicago","remote_work":false,"vacation_days_remaining":18,"overtime_hours":11.1,"email_address":"tportchmouth1q@vimeo.com"},
{"employee_id":64,"employee_name":"Emmye Shilleto","job_title":"VP Product Management","department":"Accounting","salary":141442.51,"hire_date":"11/12/2015","years_of_service":"error: expected numeric","performance_rating":1.9,"manager_name":"Seymour Beevis","team_size":16,"location":"New York","remote_work":true,"vacation_days_remaining":22,"overtime_hours":15.9,"email_address":"sbeevis1r@e-recht24.de"},
{"employee_id":65,"employee_name":"Brittan Zorzini","job_title":"Engineer IV","department":"Training","salary":49138.05,"hire_date":"12/15/2013","years_of_service":"error: expected numeric","performance_rating":1.2,"manager_name":"Robinson Hammant","team_size":14,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":23,"overtime_hours":6.6,"email_address":"rhammant1s@hc360.com"},
{"employee_id":66,"employee_name":"Monte McGhie","job_title":"VP Product Management","department":"Product Management","salary":134940.73,"hire_date":"11/8/2000","years_of_service":"error: expected numeric","performance_rating":4.2,"manager_name":"Aundrea Shadwick","team_size":3,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":20,"overtime_hours":13.4,"email_address":"ashadwick1t@cmu.edu"},
{"employee_id":67,"employee_name":"Juieta Chislett","job_title":"Media Manager III","department":"Legal","salary":75502.47,"hire_date":"8/25/2019","years_of_service":"error: expected numeric","performance_rating":4.7,"manager_name":"Carlie Billo","team_size":17,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":27,"overtime_hours":13.3,"email_address":"cbillo1u@wikimedia.org"},
{"employee_id":68,"employee_name":"Ruthie Aylett","job_title":"Administrative Assistant III","department":"Engineering","salary":116523.03,"hire_date":"6/5/2018","years_of_service":"error: expected numeric","performance_rating":4.2,"manager_name":"Joyous Cronk","team_size":2,"location":"New York","remote_work":false,"vacation_days_remaining":3,"overtime_hours":8.8,"email_address":"jcronk1v@geocities.com"},
{"employee_id":69,"employee_name":"Kim O'Sheeryne","job_title":"Occupational Therapist","department":"Accounting","salary":87952.75,"hire_date":"12/10/2013","years_of_service":"error: expected numeric","performance_rating":2.2,"manager_name":"Talya Donavan","team_size":12,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":26,"overtime_hours":18.7,"email_address":"tdonavan1w@tinypic.com"},
{"employee_id":70,"employee_name":"Eleanor Rodrigues","job_title":"GIS Technical Architect","department":"Product Management","salary":103059.3,"hire_date":"3/4/2016","years_of_service":"error: expected numeric","performance_rating":3.4,"manager_name":"Israel Coldman","team_size":13,"location":"Houston","remote_work":false,"vacation_days_remaining":27,"overtime_hours":5.3,"email_address":"icoldman1x@google.ca"},
{"employee_id":71,"employee_name":"Madelena Gilluley","job_title":"Administrative Officer","department":"Accounting","salary":78559.3,"hire_date":"11/28/2003","years_of_service":"error: expected numeric","performance_rating":1.3,"manager_name":"Lorrie Michell","team_size":14,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":19,"overtime_hours":7.2,"email_address":"lmichell1y@businessweek.com"},
{"employee_id":72,"employee_name":"Herculie Lyard","job_title":"Editor","department":"Support","salary":108814.27,"hire_date":"9/3/2002","years_of_service":"error: expected numeric","performance_rating":4.4,"manager_name":"Esra Salomon","team_size":9,"location":"Chicago","remote_work":true,"vacation_days_remaining":6,"overtime_hours":2.3,"email_address":"esalomon1z@pinterest.com"},
{"employee_id":73,"employee_name":"Madel Chilcott","job_title":"Teacher","department":"Legal","salary":131477.32,"hire_date":"11/21/2021","years_of_service":"error: expected numeric","performance_rating":4.1,"manager_name":"Hertha Songer","team_size":13,"location":"Miami","remote_work":false,"vacation_days_remaining":21,"overtime_hours":17.2,"email_address":"hsonger20@slate.com"},
{"employee_id":74,"employee_name":"Mei Rochester","job_title":"Internal Auditor","department":"Human Resources","salary":140813.37,"hire_date":"7/4/2011","years_of_service":"error: expected numeric","performance_rating":4.8,"manager_name":"Lilah Mumford","team_size":18,"location":"New York","remote_work":false,"vacation_days_remaining":9,"overtime_hours":11.6,"email_address":"lmumford21@typepad.com"},
{"employee_id":75,"employee_name":"Charin Benford","job_title":"Sales Associate","department":"Human Resources","salary":70889.6,"hire_date":"7/5/2013","years_of_service":"error: expected numeric","performance_rating":4.4,"manager_name":"Gwenora Womack","team_size":2,"location":"New York","remote_work":true,"vacation_days_remaining":29,"overtime_hours":5.6,"email_address":"gwomack22@indiegogo.com"},
{"employee_id":76,"employee_name":"Ford Hendrich","job_title":"Tax Accountant","department":"Services","salary":55784.44,"hire_date":"1/18/2015","years_of_service":"error: expected numeric","performance_rating":1.2,"manager_name":"Isidora Cumine","team_size":16,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":3,"overtime_hours":9.6,"email_address":"icumine23@4shared.com"},
{"employee_id":77,"employee_name":"Rossie Manthorpe","job_title":"Account Coordinator","department":"Human Resources","salary":143420.03,"hire_date":"3/10/2006","years_of_service":"error: expected numeric","performance_rating":3.3,"manager_name":"Hedwig Moodey","team_size":16,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":16,"overtime_hours":5.4,"email_address":"hmoodey24@ebay.co.uk"},
{"employee_id":78,"employee_name":"Carver Clegg","job_title":"Tax Accountant","department":"Business Development","salary":76713.11,"hire_date":"3/10/2002","years_of_service":"error: expected numeric","performance_rating":1.8,"manager_name":"Rosemonde Rannells","team_size":19,"location":"Chicago","remote_work":false,"vacation_days_remaining":11,"overtime_hours":6.9,"email_address":"rrannells25@ihg.com"},
{"employee_id":79,"employee_name":"Coleman Longdon","job_title":"Marketing Assistant","department":"Accounting","salary":148491.22,"hire_date":"11/6/2010","years_of_service":"error: expected numeric","performance_rating":2.0,"manager_name":"Ker Hellmore","team_size":17,"location":"Houston","remote_work":true,"vacation_days_remaining":26,"overtime_hours":7.2,"email_address":"khellmore26@addthis.com"},
{"employee_id":80,"employee_name":"Nissa Leyden","job_title":"Operator","department":"Training","salary":114418.75,"hire_date":"7/3/2008","years_of_service":"error: expected numeric","performance_rating":2.5,"manager_name":"Freeland Shorthill","team_size":5,"location":"New York","remote_work":true,"vacation_days_remaining":23,"overtime_hours":6.2,"email_address":"fshorthill27@ifeng.com"},
{"employee_id":81,"employee_name":"Terza Grabert","job_title":"Marketing Manager","department":"Services","salary":111428.14,"hire_date":"3/17/2011","years_of_service":"error: expected numeric","performance_rating":1.9,"manager_name":"Vivi Marquet","team_size":6,"location":"New York","remote_work":true,"vacation_days_remaining":13,"overtime_hours":14.2,"email_address":"vmarquet28@phpbb.com"},
{"employee_id":82,"employee_name":"Maryrose Wilkinson","job_title":"Sales Associate","department":"Support","salary":68746.74,"hire_date":"11/17/2007","years_of_service":"error: expected numeric","performance_rating":3.5,"manager_name":"Prudy Wigan","team_size":5,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":28,"overtime_hours":14.2,"email_address":"pwigan29@360.cn"},
{"employee_id":83,"employee_name":"Lamar Uccelli","job_title":"Financial Analyst","department":"Research and Development","salary":72357.86,"hire_date":"4/21/2016","years_of_service":"error: expected numeric","performance_rating":4.9,"manager_name":"Korella Karoly","team_size":12,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":17,"overtime_hours":13.9,"email_address":"kkaroly2a@skyrock.com"},
{"employee_id":84,"employee_name":"Christie Weiner","job_title":"Software Test Engineer I","department":"Services","salary":78765.2,"hire_date":"11/27/2008","years_of_service":"error: expected numeric","performance_rating":2.7,"manager_name":"Myrvyn Meak","team_size":7,"location":"Houston","remote_work":false,"vacation_days_remaining":16,"overtime_hours":7.7,"email_address":"mmeak2b@weibo.com"},
{"employee_id":85,"employee_name":"Pierre Mussilli","job_title":"Geologist IV","department":"Legal","salary":139656.83,"hire_date":"7/30/2006","years_of_service":"error: expected numeric","performance_rating":3.7,"manager_name":"Rasia Shanahan","team_size":3,"location":"New York","remote_work":true,"vacation_days_remaining":5,"overtime_hours":1.1,"email_address":"rshanahan2c@cbsnews.com"},
{"employee_id":86,"employee_name":"Bucky Giblett","job_title":"VP Product Management","department":"Support","salary":135887.04,"hire_date":"12/11/2005","years_of_service":"error: expected numeric","performance_rating":2.6,"manager_name":"Stevena Garrow","team_size":13,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":26,"overtime_hours":14.1,"email_address":"sgarrow2d@vinaora.com"},
{"employee_id":87,"employee_name":"Dareen Ovendale","job_title":"Health Coach II","department":"Engineering","salary":105869.11,"hire_date":"3/28/2010","years_of_service":"error: expected numeric","performance_rating":2.6,"manager_name":"Garik Andreou","team_size":3,"location":"Houston","remote_work":true,"vacation_days_remaining":0,"overtime_hours":10.8,"email_address":"gandreou2e@blogspot.com"},
{"employee_id":88,"employee_name":"Ezequiel de Merida","job_title":"VP Marketing","department":"Product Management","salary":43162.84,"hire_date":"8/22/2002","years_of_service":"error: expected numeric","performance_rating":3.7,"manager_name":"Emera Padula","team_size":10,"location":"Houston","remote_work":true,"vacation_days_remaining":3,"overtime_hours":0.8,"email_address":"epadula2f@pbs.org"},
{"employee_id":89,"employee_name":"Carin Bulbeck","job_title":"Nurse","department":"Training","salary":130367.32,"hire_date":"9/30/2021","years_of_service":"error: expected numeric","performance_rating":2.9,"manager_name":"Lindie Birtonshaw","team_size":4,"location":"Chicago","remote_work":false,"vacation_days_remaining":11,"overtime_hours":5.4,"email_address":"lbirtonshaw2g@pcworld.com"},
{"employee_id":90,"employee_name":"Currie Opfer","job_title":"Systems Administrator III","department":"Support","salary":129835.58,"hire_date":"1/11/2013","years_of_service":"error: expected numeric","performance_rating":4.0,"manager_name":"Langsdon Moncreif","team_size":6,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":1,"overtime_hours":19.8,"email_address":"lmoncreif2h@feedburner.com"},
{"employee_id":91,"employee_name":"Merell Langstrath","job_title":"Analyst Programmer","department":"Research and Development","salary":141400.46,"hire_date":"2/3/2019","years_of_service":"error: expected numeric","performance_rating":2.6,"manager_name":"Tallie Wewell","team_size":1,"location":"Miami","remote_work":false,"vacation_days_remaining":19,"overtime_hours":9.8,"email_address":"twewell2i@godaddy.com"},
{"employee_id":92,"employee_name":"Jessi Gorges","job_title":"Graphic Designer","department":"Research and Development","salary":68711.1,"hire_date":"11/9/2016","years_of_service":"error: expected numeric","performance_rating":3.0,"manager_name":"Elmer Windas","team_size":11,"location":"New York","remote_work":true,"vacation_days_remaining":26,"overtime_hours":3.1,"email_address":"ewindas2j@state.tx.us"},
{"employee_id":93,"employee_name":"Adrienne Reubel","job_title":"Nurse Practicioner","department":"Marketing","salary":128718.76,"hire_date":"8/27/2013","years_of_service":"error: expected numeric","performance_rating":4.5,"manager_name":"Pansie Luckwell","team_size":10,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":4,"overtime_hours":16.1,"email_address":"pluckwell2k@umn.edu"},
{"employee_id":94,"employee_name":"Kimmi Flay","job_title":"General Manager","department":"Human Resources","salary":98900.02,"hire_date":"6/18/2017","years_of_service":"error: expected numeric","performance_rating":1.7,"manager_name":"Cayla Cornell","team_size":2,"location":"Houston","remote_work":true,"vacation_days_remaining":18,"overtime_hours":2.4,"email_address":"ccornell2l@gnu.org"},
{"employee_id":95,"employee_name":"Drusilla Pethybridge","job_title":"Computer Systems Analyst II","department":"Research and Development","salary":133758.61,"hire_date":"7/13/2002","years_of_service":"error: expected numeric","performance_rating":1.9,"manager_name":"Homere Hotton","team_size":19,"location":"Miami","remote_work":false,"vacation_days_remaining":2,"overtime_hours":0.9,"email_address":"hhotton2m@ezinearticles.com"},
{"employee_id":96,"employee_name":"Cointon Fryatt","job_title":"Analog Circuit Design manager","department":"Marketing","salary":78779.49,"hire_date":"7/3/2007","years_of_service":"error: expected numeric","performance_rating":3.7,"manager_name":"Cindy Parrington","team_size":5,"location":"New York","remote_work":false,"vacation_days_remaining":28,"overtime_hours":2.0,"email_address":"cparrington2n@mlb.com"},
{"employee_id":97,"employee_name":"Hans Cashmore","job_title":"Software Consultant","department":"Legal","salary":36681.3,"hire_date":"11/20/2012","years_of_service":"error: expected numeric","performance_rating":4.7,"manager_name":"Saudra Brunelleschi","team_size":18,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":23,"overtime_hours":12.9,"email_address":"sbrunelleschi2o@fotki.com"},
{"employee_id":98,"employee_name":"Mariana Brantl","job_title":"VP Quality Control","department":"Business Development","salary":147581.92,"hire_date":"11/21/2022","years_of_service":"error: expected numeric","performance_rating":1.0,"manager_name":"Debbie Kettow","team_size":17,"location":"New York","remote_work":false,"vacation_days_remaining":3,"overtime_hours":5.0,"email_address":"dkettow2p@histats.com"},
{"employee_id":99,"employee_name":"Starlene Abel","job_title":"Geologist IV","department":"Support","salary":45494.76,"hire_date":"8/10/2010","years_of_service":"error: expected numeric","performance_rating":3.3,"manager_name":"Katerine Corradi","team_size":18,"location":"Miami","remote_work":true,"vacation_days_remaining":24,"overtime_hours":18.8,"email_address":"kcorradi2q@ehow.com"},
{"employee_id":100,"employee_name":"Francisco Orbon","job_title":"VP Sales","department":"Product Management","salary":97177.6,"hire_date":"5/8/2003","years_of_service":"error: expected numeric","performance_rating":1.3,"manager_name":"Jamima Ebenezer","team_size":12,"location":"New York","remote_work":false,"vacation_days_remaining":0,"overtime_hours":6.6,"email_address":"jebenezer2r@behance.net"},
{"employee_id":101,"employee_name":"Kassia Darcy","job_title":"Chief Design Engineer","department":"Support","salary":140383.02,"hire_date":"9/29/2020","years_of_service":"error: expected numeric","performance_rating":3.8,"manager_name":"Brigit Bayly","team_size":11,"location":"Chicago","remote_work":true,"vacation_days_remaining":30,"overtime_hours":4.3,"email_address":"bbayly2s@adobe.com"},
{"employee_id":102,"employee_name":"Linus Steeden","job_title":"Nurse Practicioner","department":"Sales","salary":129838.96,"hire_date":"11/22/2018","years_of_service":"error: expected numeric","performance_rating":3.0,"manager_name":"Reynold Clarricoates","team_size":20,"location":"Miami","remote_work":true,"vacation_days_remaining":14,"overtime_hours":11.1,"email_address":"rclarricoates2t@webs.com"},
{"employee_id":103,"employee_name":"Dermot Ryde","job_title":"Human Resources Manager","department":"Training","salary":117481.52,"hire_date":"8/4/2006","years_of_service":"error: expected numeric","performance_rating":4.3,"manager_name":"Sean Prinne","team_size":1,"location":"Houston","remote_work":true,"vacation_days_remaining":26,"overtime_hours":16.0,"email_address":"sprinne2u@mapquest.com"},
{"employee_id":104,"employee_name":"Salomone Oggers","job_title":"VP Sales","department":"Accounting","salary":74612.09,"hire_date":"10/28/2003","years_of_service":"error: expected numeric","performance_rating":1.4,"manager_name":"Franklin Largan","team_size":4,"location":"Miami","remote_work":true,"vacation_days_remaining":26,"overtime_hours":15.4,"email_address":"flargan2v@spiegel.de"},
{"employee_id":105,"employee_name":"Nancy MacCumiskey","job_title":"Operator","department":"Business Development","salary":69464.51,"hire_date":"2/21/2019","years_of_service":"error: expected numeric","performance_rating":1.3,"manager_name":"Greg Dellenty","team_size":13,"location":"Miami","remote_work":false,"vacation_days_remaining":9,"overtime_hours":11.1,"email_address":"gdellenty2w@dailymotion.com"},
{"employee_id":106,"employee_name":"Dani Pimblotte","job_title":"Assistant Media Planner","department":"Training","salary":91509.2,"hire_date":"10/18/2020","years_of_service":"error: expected numeric","performance_rating":1.1,"manager_name":"Velma Eccleston","team_size":4,"location":"Miami","remote_work":false,"vacation_days_remaining":1,"overtime_hours":2.4,"email_address":"veccleston2x@weebly.com"},
{"employee_id":107,"employee_name":"Noble Slowly","job_title":"Assistant Professor","department":"Marketing","salary":106087.14,"hire_date":"10/7/2003","years_of_service":"error: expected numeric","performance_rating":2.2,"manager_name":"Etienne Lowdyane","team_size":16,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":19,"overtime_hours":13.4,"email_address":"elowdyane2y@mayoclinic.com"},
{"employee_id":108,"employee_name":"Burgess Mc Combe","job_title":"Help Desk Operator","department":"Human Resources","salary":56663.83,"hire_date":"12/7/2019","years_of_service":"error: expected numeric","performance_rating":4.5,"manager_name":"Che Alliker","team_size":3,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":2,"overtime_hours":3.6,"email_address":"calliker2z@nps.gov"},
{"employee_id":109,"employee_name":"Gwendolin Shewan","job_title":"Media Manager I","department":"Sales","salary":46766.0,"hire_date":"3/6/2010","years_of_service":"error: expected numeric","performance_rating":2.3,"manager_name":"Philis Smither","team_size":12,"location":"Chicago","remote_work":true,"vacation_days_remaining":23,"overtime_hours":14.8,"email_address":"psmither30@eventbrite.com"},
{"employee_id":110,"employee_name":"Alane Lazonby","job_title":"Accountant II","department":"Human Resources","salary":127437.22,"hire_date":"12/27/2019","years_of_service":"error: expected numeric","performance_rating":1.3,"manager_name":"Kipper Agutter","team_size":11,"location":"Chicago","remote_work":false,"vacation_days_remaining":7,"overtime_hours":15.4,"email_address":"kagutter31@google.com.br"},
{"employee_id":111,"employee_name":"Garek By","job_title":"Electrical Engineer","department":"Training","salary":148990.55,"hire_date":"1/1/2003","years_of_service":"error: expected numeric","performance_rating":3.8,"manager_name":"Jackelyn Hayer","team_size":19,"location":"New York","remote_work":false,"vacation_days_remaining":14,"overtime_hours":16.6,"email_address":"jhayer32@ameblo.jp"},
{"employee_id":112,"employee_name":"Bettye Olennikov","job_title":"Physical Therapy Assistant","department":"Accounting","salary":75516.23,"hire_date":"2/2/2008","years_of_service":"error: expected numeric","performance_rating":3.0,"manager_name":"Linnea Grubb","team_size":17,"location":"Miami","remote_work":false,"vacation_days_remaining":11,"overtime_hours":12.0,"email_address":"lgrubb33@reference.com"},
{"employee_id":113,"employee_name":"Bibbye Crack","job_title":"Actuary","department":"Marketing","salary":77986.45,"hire_date":"4/27/2011","years_of_service":"error: expected numeric","performance_rating":5.0,"manager_name":"Rafaela Etuck","team_size":18,"location":"Chicago","remote_work":true,"vacation_days_remaining":22,"overtime_hours":4.8,"email_address":"retuck34@pagesperso-orange.fr"},
{"employee_id":114,"employee_name":"Valle Lowers","job_title":"Chief Design Engineer","department":"Accounting","salary":94722.72,"hire_date":"9/10/2020","years_of_service":"error: expected numeric","performance_rating":3.8,"manager_name":"Paco Totman","team_size":18,"location":"Miami","remote_work":true,"vacation_days_remaining":16,"overtime_hours":4.8,"email_address":"ptotman35@google.com"},
{"employee_id":115,"employee_name":"Hugh Sherratt","job_title":"Nuclear Power Engineer","department":"Support","salary":43408.33,"hire_date":"9/14/2005","years_of_service":"error: expected numeric","performance_rating":3.9,"manager_name":"Jeramie Greenfield","team_size":16,"location":"New York","remote_work":false,"vacation_days_remaining":4,"overtime_hours":11.7,"email_address":"jgreenfield36@pinterest.com"},
{"employee_id":116,"employee_name":"Philipa Grevatt","job_title":"Marketing Manager","department":"Research and Development","salary":104251.8,"hire_date":"3/12/2000","years_of_service":"error: expected numeric","performance_rating":3.5,"manager_name":"Garrik Romanin","team_size":2,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":1,"overtime_hours":4.0,"email_address":"gromanin37@stumbleupon.com"},
{"employee_id":117,"employee_name":"Hall Borgars","job_title":"Engineer IV","department":"Sales","salary":37855.21,"hire_date":"10/16/2015","years_of_service":"error: expected numeric","performance_rating":4.7,"manager_name":"Towney Giddings","team_size":1,"location":"Miami","remote_work":false,"vacation_days_remaining":10,"overtime_hours":17.2,"email_address":"tgiddings38@telegraph.co.uk"},
{"employee_id":118,"employee_name":"Anton Sowersby","job_title":"Statistician III","department":"Training","salary":97931.46,"hire_date":"2/16/2004","years_of_service":"error: expected numeric","performance_rating":4.2,"manager_name":"Arielle Howcroft","team_size":13,"location":"Houston","remote_work":true,"vacation_days_remaining":12,"overtime_hours":17.3,"email_address":"ahowcroft39@mapy.cz"},
{"employee_id":119,"employee_name":"Cort Rosgen","job_title":"Business Systems Development Analyst","department":"Human Resources","salary":82503.25,"hire_date":"7/25/2014","years_of_service":"error: expected numeric","performance_rating":3.0,"manager_name":"Sayre Prout","team_size":9,"location":"Houston","remote_work":false,"vacation_days_remaining":18,"overtime_hours":6.0,"email_address":"sprout3a@mlb.com"},
{"employee_id":120,"employee_name":"Jocelin Somerville","job_title":"Environmental Specialist","department":"Services","salary":103372.88,"hire_date":"1/7/2007","years_of_service":"error: expected numeric","performance_rating":1.4,"manager_name":"Moll Brunicke","team_size":14,"location":"Chicago","remote_work":false,"vacation_days_remaining":22,"overtime_hours":5.0,"email_address":"mbrunicke3b@angelfire.com"},
{"employee_id":121,"employee_name":"Rosmunda Parman","job_title":"Quality Engineer","department":"Services","salary":123094.1,"hire_date":"1/31/2017","years_of_service":"error: expected numeric","performance_rating":2.3,"manager_name":"Garrett Linnell","team_size":16,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":27,"overtime_hours":3.5,"email_address":"glinnell3c@google.com.hk"},
{"employee_id":122,"employee_name":"Kamilah Biddleston","job_title":"Design Engineer","department":"Research and Development","salary":121497.38,"hire_date":"11/25/2015","years_of_service":"error: expected numeric","performance_rating":2.6,"manager_name":"Camila Shadrack","team_size":5,"location":"New York","remote_work":false,"vacation_days_remaining":27,"overtime_hours":9.3,"email_address":"cshadrack3d@nhs.uk"},
{"employee_id":123,"employee_name":"Bale Filchagin","job_title":"Developer II","department":"Sales","salary":113428.56,"hire_date":"12/23/2015","years_of_service":"error: expected numeric","performance_rating":5.0,"manager_name":"Minette Tranmer","team_size":14,"location":"Chicago","remote_work":true,"vacation_days_remaining":22,"overtime_hours":11.9,"email_address":"mtranmer3e@surveymonkey.com"},
{"employee_id":124,"employee_name":"Oran Dews","job_title":"Assistant Media Planner","department":"Support","salary":119164.94,"hire_date":"10/3/2008","years_of_service":"error: expected numeric","performance_rating":3.9,"manager_name":"Brendin Layburn","team_size":16,"location":"Miami","remote_work":true,"vacation_days_remaining":7,"overtime_hours":5.4,"email_address":"blayburn3f@mediafire.com"},
{"employee_id":125,"employee_name":"Demetri Wagenen","job_title":"Senior Developer","department":"Marketing","salary":79604.78,"hire_date":"3/11/2022","years_of_service":"error: expected numeric","performance_rating":2.6,"manager_name":"Hill Eade","team_size":7,"location":"Houston","remote_work":true,"vacation_days_remaining":5,"overtime_hours":4.8,"email_address":"heade3g@salon.com"},
{"employee_id":126,"employee_name":"Liz Crutchfield","job_title":"Geological Engineer","department":"Business Development","salary":132278.43,"hire_date":"11/16/2006","years_of_service":"error: expected numeric","performance_rating":3.8,"manager_name":"Sarah Megroff","team_size":8,"location":"Chicago","remote_work":false,"vacation_days_remaining":23,"overtime_hours":0.8,"email_address":"smegroff3h@issuu.com"},
{"employee_id":127,"employee_name":"Yoshi Dockrell","job_title":"Social Worker","department":"Sales","salary":85878.35,"hire_date":"7/19/2022","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Leoline Caistor","team_size":17,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":26,"overtime_hours":13.7,"email_address":"lcaistor3i@patch.com"},
{"employee_id":128,"employee_name":"Catherin Kimmerling","job_title":"Electrical Engineer","department":"Product Management","salary":36053.15,"hire_date":"9/30/2003","years_of_service":"error: expected numeric","performance_rating":1.8,"manager_name":"Ingunna Lomis","team_size":14,"location":"Los Angeles","remote_work":true,"vacation_days_remaining":27,"overtime_hours":17.0,"email_address":"ilomis3j@surveymonkey.com"},
{"employee_id":129,"employee_name":"Finn Goulbourn","job_title":"Registered Nurse","department":"Research and Development","salary":111692.83,"hire_date":"1/13/2022","years_of_service":"error: expected numeric","performance_rating":3.5,"manager_name":"Nessie Stebbing","team_size":15,"location":"New York","remote_work":true,"vacation_days_remaining":26,"overtime_hours":4.7,"email_address":"nstebbing3k@csmonitor.com"},
{"employee_id":130,"employee_name":"Kamila Derkes","job_title":"Environmental Tech","department":"Training","salary":41578.31,"hire_date":"8/13/2021","years_of_service":"error: expected numeric","performance_rating":4.7,"manager_name":"Kayley Ipsgrave","team_size":7,"location":"New York","remote_work":false,"vacation_days_remaining":16,"overtime_hours":13.4,"email_address":"kipsgrave3l@cnn.com"},
{"employee_id":131,"employee_name":"Olin Killerby","job_title":"Accountant I","department":"Marketing","salary":59934.61,"hire_date":"3/4/2020","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Fitzgerald Mitcham","team_size":4,"location":"Miami","remote_work":true,"vacation_days_remaining":7,"overtime_hours":19.5,"email_address":"fmitcham3m@mac.com"},
{"employee_id":132,"employee_name":"Dita Shovel","job_title":"Quality Control Specialist","department":"Legal","salary":47136.25,"hire_date":"11/2/2013","years_of_service":"error: expected numeric","performance_rating":3.6,"manager_name":"Tyson Manvelle","team_size":13,"location":"Miami","remote_work":true,"vacation_days_remaining":12,"overtime_hours":3.5,"email_address":"tmanvelle3n@independent.co.uk"},
{"employee_id":133,"employee_name":"Laurel Quogan","job_title":"Senior Editor","department":"Sales","salary":142214.29,"hire_date":"3/22/2017","years_of_service":"error: expected numeric","performance_rating":3.9,"manager_name":"Royal MacElharge","team_size":2,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":18,"overtime_hours":1.3,"email_address":"rmacelharge3o@businessweek.com"},
{"employee_id":134,"employee_name":"Bennett Biggadyke","job_title":"Assistant Media Planner","department":"Human Resources","salary":48079.31,"hire_date":"4/27/2021","years_of_service":"error: expected numeric","performance_rating":2.9,"manager_name":"Faunie Fragino","team_size":13,"location":"New York","remote_work":true,"vacation_days_remaining":1,"overtime_hours":0.2,"email_address":"ffragino3p@mapquest.com"},
{"employee_id":135,"employee_name":"Haley Gierardi","job_title":"Compensation Analyst","department":"Sales","salary":137250.25,"hire_date":"8/22/2002","years_of_service":"error: expected numeric","performance_rating":3.6,"manager_name":"Matelda Hulstrom","team_size":5,"location":"Miami","remote_work":true,"vacation_days_remaining":4,"overtime_hours":1.1,"email_address":"mhulstrom3q@digg.com"},
{"employee_id":136,"employee_name":"Constance Matyasik","job_title":"Community Outreach Specialist","department":"Services","salary":101058.33,"hire_date":"7/23/2015","years_of_service":"error: expected numeric","performance_rating":2.8,"manager_name":"Hogan Andrichak","team_size":11,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":25,"overtime_hours":3.5,"email_address":"handrichak3r@elegantthemes.com"},
{"employee_id":137,"employee_name":"Woodrow Griniov","job_title":"Recruiter","department":"Support","salary":70043.03,"hire_date":"12/22/2017","years_of_service":"error: expected numeric","performance_rating":2.4,"manager_name":"Emmalyn Asey","team_size":10,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":30,"overtime_hours":18.5,"email_address":"easey3s@amazonaws.com"},
{"employee_id":138,"employee_name":"Aviva Ince","job_title":"VP Quality Control","department":"Support","salary":141075.85,"hire_date":"5/8/2002","years_of_service":"error: expected numeric","performance_rating":2.9,"manager_name":"Maurits Shortall","team_size":15,"location":"Houston","remote_work":false,"vacation_days_remaining":0,"overtime_hours":4.9,"email_address":"mshortall3t@cdbaby.com"},
{"employee_id":139,"employee_name":"Franky Gebhard","job_title":"Senior Editor","department":"Sales","salary":124316.96,"hire_date":"7/31/2013","years_of_service":"error: expected numeric","performance_rating":4.9,"manager_name":"Devy Harlick","team_size":12,"location":"Miami","remote_work":true,"vacation_days_remaining":29,"overtime_hours":17.5,"email_address":"dharlick3u@twitter.com"},
{"employee_id":140,"employee_name":"Thomasine Smallpeice","job_title":"VP Quality Control","department":"Marketing","salary":71703.89,"hire_date":"5/4/2021","years_of_service":"error: expected numeric","performance_rating":3.9,"manager_name":"Almira Capron","team_size":14,"location":"Chicago","remote_work":false,"vacation_days_remaining":6,"overtime_hours":18.9,"email_address":"acapron3v@hp.com"},
{"employee_id":141,"employee_name":"Odette Footitt","job_title":"Human Resources Assistant III","department":"Research and Development","salary":86187.08,"hire_date":"11/2/2007","years_of_service":"error: expected numeric","performance_rating":3.8,"manager_name":"Scott Gunbie","team_size":2,"location":"New York","remote_work":false,"vacation_days_remaining":29,"overtime_hours":1.2,"email_address":"sgunbie3w@mit.edu"},
{"employee_id":142,"employee_name":"Harlen Zanetto","job_title":"GIS Technical Architect","department":"Engineering","salary":66046.7,"hire_date":"7/31/2003","years_of_service":"error: expected numeric","performance_rating":4.6,"manager_name":"Barry Torrans","team_size":2,"location":"Houston","remote_work":true,"vacation_days_remaining":0,"overtime_hours":13.8,"email_address":"btorrans3x@cdc.gov"},
{"employee_id":143,"employee_name":"Putnem Herche","job_title":"Environmental Tech","department":"Training","salary":114336.25,"hire_date":"10/30/2004","years_of_service":"error: expected numeric","performance_rating":2.8,"manager_name":"Christean McFarlane","team_size":1,"location":"Houston","remote_work":true,"vacation_days_remaining":21,"overtime_hours":12.8,"email_address":"cmcfarlane3y@alibaba.com"},
{"employee_id":144,"employee_name":"Nickie Bealton","job_title":"Structural Engineer","department":"Product Management","salary":92271.66,"hire_date":"10/18/2009","years_of_service":"error: expected numeric","performance_rating":1.6,"manager_name":"Misty Kime","team_size":2,"location":"Chicago","remote_work":false,"vacation_days_remaining":21,"overtime_hours":7.0,"email_address":"mkime3z@tumblr.com"},
{"employee_id":145,"employee_name":"Ramon Samways","job_title":"Nuclear Power Engineer","department":"Research and Development","salary":134853.37,"hire_date":"7/7/2001","years_of_service":"error: expected numeric","performance_rating":4.8,"manager_name":"Ileane Lorentz","team_size":2,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":2,"overtime_hours":6.3,"email_address":"ilorentz40@nih.gov"},
{"employee_id":146,"employee_name":"Stafani Overstreet","job_title":"Senior Cost Accountant","department":"Accounting","salary":38814.1,"hire_date":"1/20/2020","years_of_service":"error: expected numeric","performance_rating":4.3,"manager_name":"Dall Jelphs","team_size":18,"location":"Houston","remote_work":false,"vacation_days_remaining":11,"overtime_hours":13.2,"email_address":"djelphs41@devhub.com"},
{"employee_id":147,"employee_name":"Corilla Staggs","job_title":"Environmental Tech","department":"Product Management","salary":38552.17,"hire_date":"12/12/2003","years_of_service":"error: expected numeric","performance_rating":3.6,"manager_name":"Melonie Faulkener","team_size":2,"location":"Miami","remote_work":true,"vacation_days_remaining":2,"overtime_hours":4.4,"email_address":"mfaulkener42@odnoklassniki.ru"},
{"employee_id":148,"employee_name":"Josias Keel","job_title":"Social Worker","department":"Services","salary":72940.22,"hire_date":"4/19/2005","years_of_service":"error: expected numeric","performance_rating":2.2,"manager_name":"Susan Holbury","team_size":14,"location":"Los Angeles","remote_work":false,"vacation_days_remaining":24,"overtime_hours":1.7,"email_address":"sholbury43@yelp.com"},
{"employee_id":149,"employee_name":"Alvan Roxby","job_title":"Quality Engineer","department":"Engineering","salary":65721.06,"hire_date":"7/14/2012","years_of_service":"error: expected numeric","performance_rating":1.1,"manager_name":"Janis Otteridge","team_size":20,"location":"Miami","remote_work":true,"vacation_days_remaining":8,"overtime_hours":3.0,"email_address":"jotteridge44@cisco.com"},
{"employee_id":150,"employee_name":"Eva Bunker","job_title":"Tax Accountant","department":"Services","salary":124083.27,"hire_date":"1/29/2005","years_of_service":"error: expected numeric","performance_rating":4.9,"manager_name":"Fawne Raynham","team_size":14,"location":"New York","remote_work":true,"vacation_days_remaining":11,"overtime_hours":18.7,"email_address":"fraynham45@icq.com"}]

1. Calculate average salary
salarys = job_data.map{|item| item[:salary]}
average = salarys.sum / salarys.size
print average.round(2)

2. Find highest performance rating 
max_ratings = job_data.max_by { |item| item[:performance_rating] }[:performance_rating]
performance_names = job_data.select { |item| item[:performance_rating] == max_ratings }.map { |item| item[:employee_name] }
print performance_names

3. years of service job_data correction
def details(job_data,current_year)
   job_data.map{|x|  current_year - x[:hire_date].split("/").last.to_i}
end 
print details(job_data, 2024)


4. Total overtime hours
print overtime_hour = job_data.sum{|item| item[:overtime_hours]}

5. Employees in chicago
locations = job_data.select { |item| item[:location] == "Chicago" }
employee_information = locations.each_with_object({}) do |details, hash|
    job_titles = details[:job_title]
    employees = details[:employee_name] 
    hash[employees] = job_titles
end
print employee_information

6. Vaction days remaining
print  job_data.max_by{|item| item[:vacation_days_remaining]}

7. Department salary analysis
departments = job_data.group_by{|item| item[:department]}
departments.each do |keys, values|
    salarys = values.sum{|item |item[:salary]}
    print keys => salarys
end 

8. Remote vs non-remote work comparision
remote_works = job_data.group_by{|item| item[:remote_work]}
remote_works.each do |keys, values|
    salarys = values.map{|item| item[:salary]}
   print keys => salarys.sum / salarys.size
end 

9. Team size analysis
manager_names = job_data.group_by{|item| item[:manager_name]}
manager_names.each do |keys, values|
    team_sizes = values.map{|item| item[:team_size]}
    average = team_sizes.sum / team_sizes.size
   print keys => average
end 

10. Email domains extraction
print job_data.map{|x| x[:email_address].split("@").last}.uniq.count
