toy_data = [{"toy_name":"Honorable","manufacturer":"Realcube","age_recommendation":"9-12 years","price":15.14,"material":"wood","color":"Orange","weight":3.2,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"11/19/2012","barcode":3991374664595,"category":"puzzles","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Avaveo","age_recommendation":"9-12 years","price":32.89,"material":"plastic","color":"Mauv","weight":1.7,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"10/5/2014","barcode":9307630010524,"category":"action figures","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mr","manufacturer":"Kaymbo","age_recommendation":"9-12 years","price":65.5,"material":"plastic","color":"Blue","weight":0.3,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"12/14/2010","barcode":7445261283992,"category":"dolls","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Ms","manufacturer":"Brainlounge","age_recommendation":"3-5 years","price":35.04,"material":"wood","color":"Indigo","weight":0.9,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"5/26/2016","barcode":7218125373565,"category":"dolls","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mrs","manufacturer":"Centimia","age_recommendation":"6-8 years","price":23.62,"material":"metal","color":"Aquamarine","weight":3.0,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"3/25/2014","barcode":6131310604975,"category":"puzzles","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mrs","manufacturer":"Zoomlounge","age_recommendation":"3-5 years","price":52.76,"material":"wood","color":"Fuscia","weight":3.6,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"9/6/2013","barcode":7329645286818,"category":"board games","battery_required":true,"packaging_type":"box"},
{"toy_name":"Ms","manufacturer":"Cogilith","age_recommendation":"3-5 years","price":71.09,"material":"wood","color":"Red","weight":4.3,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"5/31/2012","barcode":4175733116332,"category":"board games","battery_required":true,"packaging_type":"box"},
{"toy_name":"Honorable","manufacturer":"Eazzy","age_recommendation":"3-5 years","price":77.73,"material":"metal","color":"Puce","weight":4.1,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"3/31/2013","barcode":1605300661105,"category":"board games","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Honorable","manufacturer":"Fliptune","age_recommendation":"9-12 years","price":91.22,"material":"plastic","color":"Fuscia","weight":1.1,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"1/1/2019","barcode":1177806196728,"category":"puzzles","battery_required":true,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"Flipstorm","age_recommendation":"9-12 years","price":65.27,"material":"wood","color":"Mauv","weight":4.6,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"11/14/2013","barcode":9395951224926,"category":"action figures","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Ms","manufacturer":"Dynava","age_recommendation":"3-5 years","price":52.63,"material":"metal","color":"Purple","weight":1.6,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"4/8/2019","barcode":1091914328471,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Ms","manufacturer":"Quinu","age_recommendation":"3-5 years","price":29.62,"material":"plastic","color":"Maroon","weight":2.7,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"8/1/2016","barcode":3911873023326,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Honorable","manufacturer":"Flipopia","age_recommendation":"9-12 years","price":80.85,"material":"metal","color":"Green","weight":1.3,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"10/27/2019","barcode":1903478096537,"category":"board games","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Honorable","manufacturer":"Meevee","age_recommendation":"6-8 years","price":84.31,"material":"metal","color":"Khaki","weight":3.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"11/27/2011","barcode":8074087861439,"category":"puzzles","battery_required":true,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"Tavu","age_recommendation":"6-8 years","price":29.67,"material":"plastic","color":"Puce","weight":1.5,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"12/28/2010","barcode":8017615617228,"category":"puzzles","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Mr","manufacturer":"Miboo","age_recommendation":"6-8 years","price":70.68,"material":"metal","color":"Indigo","weight":1.0,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"3/26/2020","barcode":2201451014844,"category":"puzzles","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Ms","manufacturer":"Quimm","age_recommendation":"6-8 years","price":49.26,"material":"plastic","color":"Crimson","weight":4.0,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"4/16/2017","barcode":7188343606624,"category":"dolls","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Ms","manufacturer":"Devbug","age_recommendation":"3-5 years","price":53.66,"material":"wood","color":"Blue","weight":2.0,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"2/16/2014","barcode":1448049395143,"category":"dolls","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Dr","manufacturer":"Ozu","age_recommendation":"3-5 years","price":99.81,"material":"plastic","color":"Aquamarine","weight":3.4,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"6/21/2016","barcode":1461340662320,"category":"puzzles","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Mrs","manufacturer":"Plajo","age_recommendation":"3-5 years","price":71.62,"material":"plastic","color":"Maroon","weight":4.7,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"8/24/2017","barcode":6331666208599,"category":"puzzles","battery_required":true,"packaging_type":"box"},
{"toy_name":"Ms","manufacturer":"Dabtype","age_recommendation":"6-8 years","price":32.07,"material":"wood","color":"Crimson","weight":4.6,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"8/20/2016","barcode":4954961008808,"category":"action figures","battery_required":false,"packaging_type":"box"},
{"toy_name":"Rev","manufacturer":"Skinix","age_recommendation":"6-8 years","price":45.0,"material":"metal","color":"Goldenrod","weight":0.8,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"9/24/2017","barcode":4137952490317,"category":"dolls","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Dr","manufacturer":"Wikibox","age_recommendation":"6-8 years","price":95.74,"material":"plastic","color":"Pink","weight":4.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"3/4/2010","barcode":1116376433529,"category":"dolls","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Dr","manufacturer":"Dabvine","age_recommendation":"3-5 years","price":50.02,"material":"plastic","color":"Mauv","weight":2.5,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"10/4/2021","barcode":7281547369445,"category":"dolls","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Ms","manufacturer":"Youbridge","age_recommendation":"3-5 years","price":94.11,"material":"metal","color":"Aquamarine","weight":2.4,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"1/8/2017","barcode":8695581010458,"category":"action figures","battery_required":false,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"Thoughtbridge","age_recommendation":"9-12 years","price":50.88,"material":"plastic","color":"Pink","weight":3.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"12/30/2015","barcode":5260191796992,"category":"board games","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Mr","manufacturer":"Brainsphere","age_recommendation":"9-12 years","price":91.73,"material":"metal","color":"Pink","weight":3.6,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"5/22/2015","barcode":8531367394340,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Dr","manufacturer":"Riffpath","age_recommendation":"6-8 years","price":23.85,"material":"wood","color":"Green","weight":3.2,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"5/4/2019","barcode":2976706104967,"category":"action figures","battery_required":true,"packaging_type":"box"},
{"toy_name":"Rev","manufacturer":"Topdrive","age_recommendation":"6-8 years","price":98.21,"material":"plastic","color":"Goldenrod","weight":0.1,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"9/28/2014","barcode":9558839645216,"category":"action figures","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Honorable","manufacturer":"Brainsphere","age_recommendation":"9-12 years","price":78.59,"material":"metal","color":"Purple","weight":1.5,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"1/31/2011","barcode":5519245625188,"category":"board games","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mr","manufacturer":"Babblestorm","age_recommendation":"9-12 years","price":11.58,"material":"metal","color":"Orange","weight":0.2,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"8/21/2015","barcode":4741539114644,"category":"board games","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Ms","manufacturer":"Oyoba","age_recommendation":"3-5 years","price":73.01,"material":"metal","color":"Indigo","weight":0.2,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"10/13/2015","barcode":5786434875304,"category":"action figures","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Mrs","manufacturer":"Pixope","age_recommendation":"6-8 years","price":38.34,"material":"wood","color":"Maroon","weight":3.2,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"1/24/2012","barcode":2517994685320,"category":"dolls","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Rev","manufacturer":"Kazio","age_recommendation":"9-12 years","price":28.39,"material":"plastic","color":"Goldenrod","weight":0.4,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"4/21/2011","barcode":1882608668754,"category":"puzzles","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Mr","manufacturer":"Skilith","age_recommendation":"9-12 years","price":78.08,"material":"plastic","color":"Red","weight":2.8,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"11/28/2017","barcode":5930077707894,"category":"dolls","battery_required":false,"packaging_type":"box"},
{"toy_name":"Honorable","manufacturer":"Eidel","age_recommendation":"6-8 years","price":90.35,"material":"metal","color":"Maroon","weight":4.3,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"2/25/2011","barcode":4861821095297,"category":"board games","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mrs","manufacturer":"Blognation","age_recommendation":"6-8 years","price":64.88,"material":"metal","color":"Pink","weight":2.7,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"2/9/2010","barcode":2650881283246,"category":"board games","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mrs","manufacturer":"Youfeed","age_recommendation":"3-5 years","price":28.1,"material":"plastic","color":"Aquamarine","weight":0.9,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"8/14/2017","barcode":9387694155526,"category":"action figures","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mrs","manufacturer":"Rhyloo","age_recommendation":"6-8 years","price":45.03,"material":"plastic","color":"Fuscia","weight":3.5,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"11/22/2015","barcode":3266503414318,"category":"board games","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Mr","manufacturer":"Feedfire","age_recommendation":"9-12 years","price":24.29,"material":"wood","color":"Pink","weight":1.0,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"11/25/2018","barcode":7861725600137,"category":"dolls","battery_required":false,"packaging_type":"box"},
{"toy_name":"Ms","manufacturer":"Fadeo","age_recommendation":"9-12 years","price":12.64,"material":"wood","color":"Maroon","weight":2.1,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"6/26/2010","barcode":7058262805073,"category":"action figures","battery_required":true,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"Babbleopia","age_recommendation":"6-8 years","price":30.24,"material":"wood","color":"Aquamarine","weight":2.1,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"4/7/2015","barcode":5632825798784,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Mr","manufacturer":"Yotz","age_recommendation":"6-8 years","price":90.96,"material":"metal","color":"Green","weight":4.4,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"1/11/2021","barcode":9396764167277,"category":"action figures","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Reallinks","age_recommendation":"3-5 years","price":36.2,"material":"wood","color":"Green","weight":0.9,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"4/5/2015","barcode":5051579941505,"category":"board games","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Rev","manufacturer":"Dabtype","age_recommendation":"9-12 years","price":82.59,"material":"plastic","color":"Goldenrod","weight":2.7,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"9/16/2021","barcode":5711586486879,"category":"action figures","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Mrs","manufacturer":"Mybuzz","age_recommendation":"6-8 years","price":88.58,"material":"metal","color":"Turquoise","weight":2.1,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"5/10/2020","barcode":7032922457689,"category":"board games","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Mrs","manufacturer":"Plambee","age_recommendation":"6-8 years","price":66.69,"material":"wood","color":"Yellow","weight":3.4,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"7/10/2016","barcode":4175224727660,"category":"dolls","battery_required":false,"packaging_type":"box"},
{"toy_name":"Rev","manufacturer":"Dabtype","age_recommendation":"3-5 years","price":48.78,"material":"plastic","color":"Blue","weight":3.4,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"10/10/2013","barcode":3657387309300,"category":"action figures","battery_required":false,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"BlogXS","age_recommendation":"9-12 years","price":14.45,"material":"metal","color":"Pink","weight":0.4,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"10/30/2014","barcode":2701910133378,"category":"board games","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Mr","manufacturer":"Rhyloo","age_recommendation":"9-12 years","price":76.37,"material":"wood","color":"Turquoise","weight":1.6,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"10/26/2013","barcode":8523059744975,"category":"dolls","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Dr","manufacturer":"Edgeblab","age_recommendation":"3-5 years","price":41.71,"material":"metal","color":"Indigo","weight":4.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"2/8/2013","barcode":5829085548656,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Rev","manufacturer":"Kamba","age_recommendation":"3-5 years","price":83.89,"material":"wood","color":"Pink","weight":1.6,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"8/22/2012","barcode":4459798375163,"category":"action figures","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Dr","manufacturer":"Vipe","age_recommendation":"3-5 years","price":91.54,"material":"metal","color":"Pink","weight":3.8,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"4/20/2015","barcode":9129090341794,"category":"action figures","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Mr","manufacturer":"Topicblab","age_recommendation":"6-8 years","price":45.28,"material":"metal","color":"Mauv","weight":4.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"10/6/2017","barcode":2467376953663,"category":"board games","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Dr","manufacturer":"Brainbox","age_recommendation":"9-12 years","price":87.47,"material":"metal","color":"Red","weight":3.3,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"6/8/2021","barcode":9564649091816,"category":"action figures","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Izio","age_recommendation":"6-8 years","price":78.21,"material":"plastic","color":"Red","weight":4.5,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"12/9/2021","barcode":4409510017664,"category":"board games","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Rev","manufacturer":"Bluezoom","age_recommendation":"3-5 years","price":7.11,"material":"wood","color":"Green","weight":1.8,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"9/23/2013","barcode":4508761184145,"category":"board games","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Mrs","manufacturer":"Skyble","age_recommendation":"9-12 years","price":99.8,"material":"plastic","color":"Pink","weight":3.2,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"2/21/2020","barcode":3866047926622,"category":"puzzles","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Jaxworks","age_recommendation":"6-8 years","price":29.21,"material":"wood","color":"Fuscia","weight":3.4,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"5/3/2010","barcode":9455226726093,"category":"board games","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Honorable","manufacturer":"Zoomdog","age_recommendation":"6-8 years","price":86.05,"material":"plastic","color":"Aquamarine","weight":4.3,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"2/2/2020","barcode":5287693930466,"category":"board games","battery_required":false,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"Yodo","age_recommendation":"3-5 years","price":98.26,"material":"metal","color":"Crimson","weight":2.1,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"2/27/2010","barcode":5460410229309,"category":"dolls","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Mrs","manufacturer":"Tagfeed","age_recommendation":"3-5 years","price":88.95,"material":"metal","color":"Violet","weight":1.0,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"3/16/2014","barcode":4974949219810,"category":"board games","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Dr","manufacturer":"Skinix","age_recommendation":"6-8 years","price":37.73,"material":"plastic","color":"Fuscia","weight":4.6,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"7/30/2012","barcode":3246146326548,"category":"puzzles","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Rev","manufacturer":"Snaptags","age_recommendation":"6-8 years","price":24.78,"material":"plastic","color":"Khaki","weight":4.4,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"8/5/2013","barcode":3281893832371,"category":"dolls","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Rev","manufacturer":"Twinte","age_recommendation":"9-12 years","price":72.67,"material":"plastic","color":"Green","weight":3.2,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"12/21/2014","barcode":8331485898137,"category":"action figures","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Mr","manufacturer":"Meevee","age_recommendation":"6-8 years","price":34.66,"material":"wood","color":"Orange","weight":2.7,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"5/15/2014","barcode":2658447349121,"category":"puzzles","battery_required":false,"packaging_type":"box"},
{"toy_name":"Honorable","manufacturer":"Aimbo","age_recommendation":"3-5 years","price":68.99,"material":"metal","color":"Khaki","weight":3.6,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"8/23/2010","barcode":6490716352974,"category":"dolls","battery_required":true,"packaging_type":"box"},
{"toy_name":"Honorable","manufacturer":"Photospace","age_recommendation":"3-5 years","price":60.36,"material":"wood","color":"Orange","weight":0.4,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"1/17/2014","barcode":3240802605343,"category":"board games","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Honorable","manufacturer":"Wordpedia","age_recommendation":"6-8 years","price":75.82,"material":"plastic","color":"Goldenrod","weight":1.7,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"9/16/2012","barcode":5151554114787,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Ms","manufacturer":"Rhyloo","age_recommendation":"9-12 years","price":8.34,"material":"metal","color":"Yellow","weight":0.6,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"6/10/2014","barcode":1916905830418,"category":"board games","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Honorable","manufacturer":"Devbug","age_recommendation":"6-8 years","price":75.38,"material":"metal","color":"Mauv","weight":0.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"8/10/2019","barcode":1741835659052,"category":"puzzles","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Mr","manufacturer":"Agimba","age_recommendation":"3-5 years","price":98.04,"material":"metal","color":"Puce","weight":0.2,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"1/20/2013","barcode":7772982217583,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Honorable","manufacturer":"Cogidoo","age_recommendation":"3-5 years","price":86.04,"material":"metal","color":"Green","weight":4.1,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"5/4/2012","barcode":6678458041919,"category":"action figures","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Blogspan","age_recommendation":"3-5 years","price":12.77,"material":"metal","color":"Teal","weight":3.6,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"12/21/2019","barcode":9167207926380,"category":"dolls","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Honorable","manufacturer":"Blogtags","age_recommendation":"3-5 years","price":74.06,"material":"metal","color":"Mauv","weight":4.5,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"2/14/2021","barcode":8586901338507,"category":"dolls","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Dynabox","age_recommendation":"6-8 years","price":72.18,"material":"wood","color":"Crimson","weight":4.6,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"2/21/2020","barcode":6451197415209,"category":"board games","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Honorable","manufacturer":"Yadel","age_recommendation":"3-5 years","price":93.89,"material":"wood","color":"Orange","weight":3.8,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"3/2/2015","barcode":3712777900120,"category":"board games","battery_required":false,"packaging_type":"box"},
{"toy_name":"Ms","manufacturer":"Skiba","age_recommendation":"9-12 years","price":81.07,"material":"metal","color":"Turquoise","weight":2.4,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"5/21/2016","barcode":4816536057874,"category":"board games","battery_required":true,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"Rhynyx","age_recommendation":"6-8 years","price":72.54,"material":"metal","color":"Puce","weight":2.2,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"6/12/2010","barcode":4761123077385,"category":"dolls","battery_required":false,"packaging_type":"box"},
{"toy_name":"Rev","manufacturer":"Zoombox","age_recommendation":"9-12 years","price":8.51,"material":"plastic","color":"Purple","weight":1.6,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"2/8/2012","barcode":6161787845338,"category":"puzzles","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Demimbu","age_recommendation":"9-12 years","price":52.83,"material":"plastic","color":"Maroon","weight":3.9,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"8/4/2012","barcode":4068344094629,"category":"puzzles","battery_required":false,"packaging_type":"box"},
{"toy_name":"Mr","manufacturer":"Zoomdog","age_recommendation":"9-12 years","price":23.15,"material":"wood","color":"Purple","weight":1.3,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"3/26/2019","barcode":9879143166036,"category":"board games","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Rev","manufacturer":"Bubblebox","age_recommendation":"3-5 years","price":91.98,"material":"metal","color":"Purple","weight":4.0,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"2/13/2020","barcode":8331128819385,"category":"action figures","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Topicblab","age_recommendation":"9-12 years","price":53.06,"material":"plastic","color":"Purple","weight":1.5,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":false,"release_date":"1/31/2017","barcode":6827981317908,"category":"board games","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Ms","manufacturer":"Blogtag","age_recommendation":"9-12 years","price":65.81,"material":"wood","color":"Violet","weight":2.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"7/4/2019","barcode":8678822870176,"category":"action figures","battery_required":false,"packaging_type":"box"},
{"toy_name":"Dr","manufacturer":"Roombo","age_recommendation":"9-12 years","price":61.73,"material":"metal","color":"Pink","weight":3.9,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"8/19/2010","barcode":5134124421098,"category":"board games","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Mr","manufacturer":"Quatz","age_recommendation":"3-5 years","price":99.38,"material":"metal","color":"Crimson","weight":2.1,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"11/3/2013","barcode":7666052628686,"category":"board games","battery_required":true,"packaging_type":"blister pack"},
{"toy_name":"Dr","manufacturer":"Vitz","age_recommendation":"3-5 years","price":11.14,"material":"wood","color":"Violet","weight":1.8,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"3/23/2019","barcode":4363367561059,"category":"dolls","battery_required":true,"packaging_type":"box"},
{"toy_name":"Mr","manufacturer":"Npath","age_recommendation":"9-12 years","price":95.7,"material":"plastic","color":"Fuscia","weight":0.7,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"6/6/2016","barcode":3523524991605,"category":"puzzles","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Ms","manufacturer":"Innojam","age_recommendation":"3-5 years","price":28.0,"material":"wood","color":"Indigo","weight":3.6,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"12/16/2020","barcode":4978202157829,"category":"action figures","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Fivebridge","age_recommendation":"9-12 years","price":74.35,"material":"metal","color":"Pink","weight":3.1,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"9/15/2014","barcode":4474889180350,"category":"puzzles","battery_required":true,"packaging_type":"box"},
{"toy_name":"Mr","manufacturer":"Kwideo","age_recommendation":"6-8 years","price":48.68,"material":"plastic","color":"Red","weight":2.2,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"9/14/2018","barcode":4748451062401,"category":"board games","battery_required":false,"packaging_type":"box"},
{"toy_name":"Rev","manufacturer":"Tagpad","age_recommendation":"3-5 years","price":99.85,"material":"plastic","color":"Violet","weight":1.1,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":false,"release_date":"9/24/2015","barcode":9562438528517,"category":"dolls","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Honorable","manufacturer":"Buzzshare","age_recommendation":"9-12 years","price":14.29,"material":"plastic","color":"Khaki","weight":4.3,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"10/26/2014","barcode":1925105834881,"category":"board games","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Honorable","manufacturer":"Flashset","age_recommendation":"9-12 years","price":29.08,"material":"metal","color":"Turquoise","weight":2.9,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":true,"release_date":"6/28/2018","barcode":8442939689490,"category":"dolls","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Rev","manufacturer":"Vipe","age_recommendation":"6-8 years","price":10.68,"material":"plastic","color":"Yellow","weight":2.8,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"9/27/2015","barcode":2657749277975,"category":"action figures","battery_required":false,"packaging_type":"blister pack"},
{"toy_name":"Dr","manufacturer":"Buzzshare","age_recommendation":"3-5 years","price":9.0,"material":"plastic","color":"Turquoise","weight":0.8,"dimensions":"error: Field 'length' not found","recommended_gender":"unisex","assembly_required":true,"release_date":"6/5/2020","barcode":6097099243636,"category":"board games","battery_required":true,"packaging_type":"bag"},
{"toy_name":"Mrs","manufacturer":"Jabberbean","age_recommendation":"3-5 years","price":56.75,"material":"metal","color":"Turquoise","weight":4.5,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"3/17/2015","barcode":6822781886354,"category":"puzzles","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Dr","manufacturer":"BlogXS","age_recommendation":"3-5 years","price":54.18,"material":"metal","color":"Pink","weight":1.0,"dimensions":"error: Field 'length' not found","recommended_gender":"girls","assembly_required":true,"release_date":"9/19/2020","barcode":2485170420338,"category":"puzzles","battery_required":false,"packaging_type":"bag"},
{"toy_name":"Ms","manufacturer":"Kaymbo","age_recommendation":"3-5 years","price":92.66,"material":"metal","color":"Green","weight":3.0,"dimensions":"error: Field 'length' not found","recommended_gender":"boys","assembly_required":false,"release_date":"7/29/2011","barcode":8681457715090,"category":"board games","battery_required":true,"packaging_type":"bag"}]

# 1. Filter toys by age recommendation 
toy_names = toy_data.group_by{|item| item[:toy_name]}
toy_names.each do |keys,values|
   age_recommendations =  values.select{|item| item[:age_recommendation] == "9-12 years"}
  print keys => age_recommendations.map{|item| item[:age_recommendation]}.count
end 

# 2. calculate average price
toy_names = toy_data.group_by{|item| item[:toy_name]}
toy_names.each do |keys,values|
    prices = values.select{|item| item[:price]}.map{|item| item[:price]}
    average = prices.sum/ prices.size
    print keys => average.round(2)
end 

# 3. Find toys requiring batteries
battery_requireds =  toy_data.select{|item| item [:battery_required]}
toy_names = battery_requireds.map{|item| item[:toy_name]}.uniq
print toy_names

# 4. Sort toys by price
toy_names = toy_data.group_by{|item| item[:toy_name]  }
toy_names.each do |keys,values|
sort_prices = values.map{|item| item[:price]}.sort
  print keys => sort_prices
end

# 5. Count toys by category 
categorys = toy_data.group_by{|item| item[:category]}
categorys.each do |keys,values|
count_category = values.map{|item| item[:category]}.count
print keys => count_category
end

# 6.Find toys with missing dimensions 
toy_names = toy_data.group_by{|item| item[:toy_name]}
toy_names.each do |keys,values|
dimensions = values.map{|item| item[:dimensions]}
print keys => dimensions
end 

# 7. Filter toys by material and color
toy_names = toy_data.group_by{|item| item[:toy_name]}
toy_names.each do |keys,values|
    materials_colors = values.map{|item| [item[:material],item[:color]]}
 print keys => materials_colors
end 

# 8. Check if assembly is required for all toys
print toy_data.any?{|item| item[:assembly_required]}

#9. Group toys by manufacturer 
toy_names = toy_data.group_by{|item| item[:toy_name]}
toy_names.each do |keys,values|
    manufacturers = values.map{|item| item[:manufacturer]}
    print keys => manufacturers
end 

# 10. Find most expensive toy 
prices = toy_data.max_by{|item| item[:price]}
toy_names = prices[:toy_name]
price = prices[:price]
print toy_names => price